EventSte/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('events/',include('events.urls')),
    path('bookings/',include('bookings.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

events/urls.py
from django.urls import include,path
from . import views
# from .views import OrganizerRegistrationView, ClientRegistrationView
from django.contrib.auth.decorators import login_required
app_name = 'events'


urlpatterns = [
    path('organizer', login_required(views.index1), name='manage_org'),
    path('admin', login_required(views.index2), name='manage_adm'),
    path('create/', login_required(views.create_event), name='create'),
    path('update/<int:event_id>/', login_required(views.update_event), name='update_event'),
     path('<int:event_id>/', views.event_detail, name='event_detail'),
    path('event/validate/<int:event_id>/', login_required(views.validate_event), name='validate_event'),
    path('', views.event_listing, name='event_listing'),
]

users/urls.py
# urls.py
from django.urls import path
from . import views
# from .views import OrganizerRegistrationView, ClientRegistrationView
from django.contrib.auth.decorators import login_required


urlpatterns = [
path('', views.index, name= 'index'),
path('login/', views.login_view, name='login_view'),
path('register_client/', views.register_client, name='registercli'),
path('register_organizer/', views.register_organizer, name='registerorg'),
path('Dashboard/', login_required(views.dashboard_show), name='dash'),
path('logout/', views.logout_view, name='logout'),
# path('search/', views.event_search, name='event_search'),
path('search/', views.search_events, name='search_events'),
path('clients/admin/', login_required(views.manage_clients), name='manage_clients'),
path('organizers/admin/', login_required(views.manage_organizers), name='manage_organizers'),
path('validate_organizer/<int:id>/', login_required(views.validate_organizer), name='validate_organizer'),
path('profile/admin/', login_required(views.admin_profile), name='admin_profile'),
path('organizer/profile/', login_required(views.organizer_profile), name='organizer_profile'),
path('client/profile/',login_required(views.client_profile), name='client_profile'),
 path('organizer/deactivate/<int:organizer_id>/', login_required(views.deactivate_organizer), name='deactivate_organizer'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
# from event.models import Event,EventCategory,Category
# Create your models here.
# models.py
class User(AbstractUser) :
    pass
class Organizer(User):
    phone_number = models.CharField(max_length=20)
    description = models.TextField()
    image = models.ImageField(upload_to='organizer_images/')
    social_media_link = models.URLField(blank=True)

    # Additional fields and methods specific to the Organizer model

class Client(User):
    birthdate = models.DateField()
    phone_number = models.CharField(max_length=20)
    image = models.ImageField(upload_to='client_images/')
    cin = models.CharField(max_length=20)
    @property
    def is_client(self):
        return True
    # Additional fields and methods specific to the Client model
    
# class TicketType(models.Model):
#     TicketType_id = models.AutoField(primary_key=True)
#     event = models.ForeignKey(Event, on_delete=models.CASCADE)
#     name = models.CharField(max_length=100)
#     price = models.DecimalField(max_digits=8, decimal_places=2)
#     quantity = models.PositiveIntegerField()
#     reated_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return self.name

# class Booking(models.Model):
#     booking_id = models.AutoField(primary_key=True)
#     client = models.ForeignKey(User, on_delete=models.CASCADE)
#     event = models.ForeignKey(Event, on_delete=models.CASCADE)
#     total_price = models.DecimalField(max_digits=8, decimal_places=2)
#     status_choices = [
#         ('pending', 'Pending'),
#         ('confirmed', 'Confirmed'),
#         ('cancelled', 'Cancelled'),
#     ]
#     status = models.CharField(max_length=20, choices=status_choices, default='pending')
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return f"Booking #{self.booking_id} - {self.client.username}"
    
# class BookingTicketInfo(models.Model):
    
#     id = models.AutoField(primary_key=True)
#     ticket_type = models.ForeignKey(TicketType, on_delete=models.CASCADE)
#     booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
#     quantity = models.PositiveIntegerField()
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return f"Booking Ticket Info #{self.id} - {self.ticket_type.name}"

users/views.py
# views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import OrganizerForm, ClientForm,LoginForm
from .models import Client, Organizer, User 
from bookings.models import Booking
from events.models import Event,EventCategory,Category
from django.contrib.auth import logout
from django.http import HttpResponseForbidden
from django.db.models import Q


def register_organizer(request):
    user = request.user
    if user.is_authenticated:
        return redirect('dash')
    else:
        organizer_form = OrganizerForm(request.POST, request.FILES)
        if request.method == 'POST':
            if organizer_form.is_valid():
                user = organizer_form.save(commit=False)
                user.set_password(organizer_form.cleaned_data['password'])
                # user.is_active = False  # Set the is_active flag to True
                user.save()
                return redirect('login_view')   # Redirect to the desired page after successful registration
            else : 
                context = {
            'organizer_form': organizer_form
        }
                return render(request, 'register_organizer.html',context)
        else:
            organizer_form = OrganizerForm()
        context = {
            'organizer_form': organizer_form
        }
        return render(request, 'register_organizer.html', context)
        

def register_client(request):
    user = request.user
    if user.is_authenticated:
        return redirect('dash')
    else:
        form = ClientForm(request.POST, request.FILES)
        if request.method == 'POST':
            if form.is_valid():
                user = form.save(commit=False)
                user.set_password(form.cleaned_data['password'])
                user.save()
                return redirect('login_view')  # Redirect to the desired page after successful registration
            else : 
                context = {
            'client_form': form,
        }
                return render(request, 'register_client.html',context)
        else:
            client_form = ClientForm() 
        context = {
            'client_form': client_form
        }
        return render(request, 'register_client.html', context)

def login_view(request):
    user = request.user
    if user.is_authenticated:
        return redirect('/')
    else :
        form = LoginForm(request, data=request.POST)
        if request.method == 'POST':
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('/')    
            else:
                context = {
                    'form': form,
                }
                return render(request, 'login.html', context)
        else :
            f = LoginForm()
            return render(request, 'login.html', {'form': f})

def logout_view(request):
    logout(request)
    return redirect('index')  # Replace 'home' with the URL or name of your desired homepage
from django.db.models import Sum

def dashboard_show(request):
    user = request.user
    if hasattr(user, 'organizer'):
          # Get the search query from the request GET parameters
        events = Event.objects.filter( Q(location__icontains='agadir'))
        aga = events.count()
        events = Event.objects.filter( Q(location__icontains='casa'))
        casa = events.count()
        event_count = user.event_set.count()
        events = Event.objects.filter(organizer=user)
        confirmed_bookings = Booking.objects.filter(event__in=events, status='confirmed')
        total_earnings = confirmed_bookings.aggregate(Sum('total_price'))['total_price__sum']
        if total_earnings is None : total_earnings = 0
        total_bookings = confirmed_bookings.count()
        context = {'event_count': event_count,
                   'total_earnings': total_earnings,
                   'total_bookings' : total_bookings,
                   'casa' : casa,
                   'aga' : aga,
                   }
        return render(request, 'Dashboard-organizer.html',context)
    elif hasattr(user, 'client'):
        bk = Booking.objects.filter(client=user, status='confirmed')
        bks = bk[1:3]
        total_bookings = bk.count()
        total_spending = bk.aggregate(sum_total=Sum('total_price'))
        total_spending = total_spending['sum_total'] or 0
        context = {'total_bookings': total_bookings,
                   'total_spending': total_spending,
                   'bks' : bks,
                   }
        return render(request, 'Dashboard-client.html',context)
    elif user.is_superuser: 
        context = {
        'total_events_count': Event.objects.count(),
        'total_organizers_count': Organizer.objects.count(),
        'total_clients_count': Client.objects.count(),
        }
        return render(request, 'Dashboard-admin.html',context)


def index(request):
     categories = Category.objects.all()
     context = {'categories': categories}
     return render(request,'index.html',context)

# def event_search(request):
#     query = request.GET.get('EventName', '')  # Get the search query from the request GET parameters
#     events = Event.objects.filter(
#         Q(name__icontains=query) |        # Search by event name (case-insensitive)
#         Q(location__icontains=query)   # Search by city (case-insensitive)
#     ).filter(status="confirmed").distinct()
#     context = {
#         'query': query,
#         'events': events,
#         'categories' : Category.objects.all(),
#     }

def search_events(request):
    query = request.GET.get('EventName', '')  # Get the search query from the request GET parameters
    events = Event.objects.filter(status="confirmed")
    if query :
        events = events.filter(
            Q(name__icontains=query) |        # Search by event name (case-insensitive)
            Q(location__icontains=query) |
            Q(description__icontains=query)  # Search by city (case-insensitive)
        ).distinct()
    category_id = request.GET.get('category')
    if category_id:
        category = Category.objects.get(category_id=category_id)
        events = events.filter(categories=category)
    Date = request.GET.get('Date')

    if Date : 
        events = events.filter(start_datetime__date=Date)
    
    Price = request.GET.get('Price')
    if Price:
        events = events.filter(standard__lte=Price)
        
    categories = Category.objects.all()
    context = {
        'categories' :categories,
        'events': events,
    }
    return render(request,'event_listing.html',context)

def manage_clients(request):
    clients = Client.objects.all()
    return render(request, 'manage_clients.html', {'clients': clients})

def manage_organizers(request):
    organizers = Organizer.objects.all()
    for organizer in organizers:
        event_count = organizer.event_set.count()
        organizer.event_count = event_count
    return render(request, 'manage_organizers.html', {'organizers': organizers})


def validate_organizer(request, id):
    organizer = Organizer.objects.get(id=id)
        # Perform validation logic here
    organizer.is_active = True
    organizer.save()
        # Redirect to a success page or a different URL
    return redirect('manage_organizers')

def admin_profile(request):
    return render(request, 'admin_profile.html')

def organizer_profile(request):
    return render(request, 'organizer_profile.html')

def client_profile(request):
    return render(request, 'client_profile.html')

def deactivate_organizer(request, organizer_id):
    organizer = Organizer.objects.get(id=organizer_id)
    organizer.is_active = False
    organizer.save()
    return redirect('manage_organizers') 

users/templates/Dashboard-admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - Mazer Admin Dashboard</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../static/css/bootstrap.css">

    <link rel="stylesheet" href="../../static/vendors/iconly/bold.css">

    <link rel="stylesheet" href="../../static/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="../../static/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="../../static/css/app.css">
    <link rel="shortcut icon" href="../static/images/favicon.svg" type="image/x-icon">
</head>
<body>
    <div id="app">
        {% include 'admin_sidebar.html' %}
        <div id="main">
            <header class="mb-3">
                <a href="#" class="burger-btn d-block d-xl-none">
                    <i class="bi bi-justify fs-3"></i>
                </a>
            </header>

            <div class="page-heading">
                <h3>{{user.username}} - Statistics</h3>
            </div>
            <div class="page-content">
                <section class="row">
                    <div class="col-12 col-lg-12">
                        <div class="row">
                            <div class="col-6 col-lg-4 col-md-6">
                                <div class="card">
                                    <div class="card-body px-3 py-4-5">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="stats-icon green">
                                                    <i class="iconly-boldShow"></i>
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <h6 class="text-muted font-semibold">Current events</h6>
                                                <h6 class="font-extrabold mb-0">{{total_events_count}}</h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 col-lg-4 col-md-6">
                                <div class="card">
                                    <div class="card-body px-3 py-4-5">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="stats-icon blue">
                                                    <i class="iconly-boldProfile"></i>
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <h6 class="text-muted font-semibold">Organizers</h6>
                                                <h6 class="font-extrabold mb-0">{{total_organizers_count}}</h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 col-lg-4 col-md-6">
                                <div class="card">
                                    <div class="card-body px-3 py-4-5">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="stats-icon green">
                                                    <i class="iconly-boldAdd-User"></i>
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <h6 class="text-muted font-semibold">Users</h6>
                                                <h6 class="font-extrabold mb-0">{{total_clients_count}}</h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12 col-xl-4">
                                <div class="card">
                                    <div class="card-header">
                                        <h4>Event by City</h4>
                                    </div>
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-6">
                                                <div class="d-flex align-items-center">
                                                    <svg class="bi text-primary" width="32" height="32" fill="blue"
                                                         style="width:10px">
                                                        <use
                                                                xlink:href="assets/vendors/bootstrap-icons/bootstrap-icons.svg#circle-fill" />
                                                    </svg>
                                                    <h5 class="mb-0 ms-3">Agadir</h5>
                                                </div>
                                            </div>
                                            <div class="col-6">
                                                <h5 class="mb-0">862</h5>
                                            </div>
                                            <div class="col-12">
                                                <div id="chart-europe"></div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-6">
                                                <div class="d-flex align-items-center">
                                                    <svg class="bi text-success" width="32" height="32" fill="blue"
                                                         style="width:10px">
                                                        <use
                                                                xlink:href="assets/vendors/bootstrap-icons/bootstrap-icons.svg#circle-fill" />
                                                    </svg>
                                                    <h5 class="mb-0 ms-3">Casa</h5>
                                                </div>
                                            </div>
                                            <div class="col-6">
                                                <h5 class="mb-0">375</h5>
                                            </div>
                                            <div class="col-12">
                                                <div id="chart-america"></div>
                                            </div>
                                        </div>
                                       
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-xl-8">
                                <div class="card">
                                    <div class="card-header">
                                        <h4>Latest Contact Us</h4>
                                    </div>
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table class="table table-hover table-lg">
                                                <thead>
                                                <tr>
                                                    <th>Name</th>
                                                    <th>Comment</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td class="col-3">
                                                        <div class="d-flex align-items-center">
                                                            <div class="avatar avatar-md">
                                                                <img src="../../static/images/faces/5.jpg">
                                                            </div>
                                                            <p class="font-bold ms-3 mb-0">Ayoub Ait</p>
                                                        </div>
                                                    </td>
                                                    <td class="col-auto">
                                                        <p class=" mb-0">i love it!</p>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="col-3">
                                                        <div class="d-flex align-items-center">
                                                            <div class="avatar avatar-md">
                                                                <img src="../../static/images/faces/2.jpg">
                                                            </div>
                                                            <p class="font-bold ms-3 mb-0">Jamal Ouh</p>
                                                        </div>
                                                    </td>
                                                    <td class="col-auto">
                                                        <p class=" mb-0">great event site</p>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </section>
            </div>

            <footer>
                <div class="footer clearfix mb-0 text-muted">
                    <div class="float-start">
                        <p>2023 &copy; AYB @ JML</p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="../../static/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="../../static/js/bootstrap.bundle.min.js"></script>

    <script src="../../static/vendors/apexcharts/apexcharts.js"></script>
    <script src="../../static/js/pages/dashboard.js"></script>

    <script src="../../static/js/main/main.js"></script>
</body>

</html>

users/templates/admin_sidebar.html
<div id="sidebar" class="active">
    <div class="sidebar-wrapper active">
        <div class="sidebar-header">
            <div class="d-flex justify-content-between">
                <div class="logo">
                    <a href="/"><img src="../../static/images/logo/logo.png" alt="Logo" id='logo' srcset="" style="
                        height: 100%;
                    "></a>
                </div>
                <div class="toggler">
                    <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                </div>
            </div>
        </div>
        <div class="sidebar-menu">
            <ul class="menu">
                <li class="sidebar-title">Menu</li>

                <li class="sidebar-item  ">
                    <a href="/Dashboard" class='sidebar-link'>
                        <i class="bi bi-grid-fill"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li class="sidebar-item  has-sub">
                    <a href="#" class='sidebar-link'>
                        <i class="bi bi-calendar3-event"></i>
                        <span>Events</span>
                    </a>
                    <ul class="submenu ">
                        <li class="submenu-item ">
                            <a href="{% url 'events:manage_adm' %}">Manage</a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-item  has-sub">
                    <a href="#" class='sidebar-link'>
                        <i class="bi bi-person"></i>
                        <span>Organizers</span>
                    </a>
                    <ul class="submenu ">
                        <li class="submenu-item ">
                            <a href="{% url 'manage_organizers' %}">Manage</a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-item  has-sub">
                    <a href="#" class='sidebar-link'>
                        <i class="bi bi-person-plus-fill"></i>
                        <span>Users</span>
                    </a>
                    <ul class="submenu ">
                        <li class="submenu-item ">
                            <a href="{% url 'manage_clients' %}">Manage</a>
                        </li>
                    </ul>
                </li>
      
                <li class="sidebar-item  has-sub">
                    <a href="#" class='sidebar-link'>
                        <i class="bi bi-person-badge"></i>
                        <span>My profile</span>
                    </a>
                    <ul class="submenu ">
                        <li class="submenu-item ">
                            <a href="{% url 'admin_profile' %}">Manage</a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-item">
                    <a href="{% url 'logout' %}" class='sidebar-link'>
                        <i class="bi bi-box-arrow-right"></i>
                        <span>Log Out</span>
                    </a>
                </li>

                <!--<li class="sidebar-title">Forms &amp; Tables</li>-->

            </ul>
        </div>
        <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
    </div>
</div>

users/templates/header_component.html
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="/" class="logo d-flex align-items-center me-auto me-lg-0">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>Eventino<span>.</span></h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#categories">Categories</a></li>
          <li><a href="{% url 'events:event_listing' %}">Events</a></li>
          <li><a href="#gallery">Gallery</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'dash' %}">Dashboard</a></li> 
         <li><a href="{% url 'logout' %}" class='sidebar-link'>
         
          <span>Log Out</span>
      </a></li> 
          {% else %}
         <li class="dropdown"><a href="#">Sign in</a></i>
            <ul>
              <li class="dropdown"><a href="#"><span>User</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                <ul>
                  <li><a href="{% url 'login_view' %}">Log in</a></li>
                  <li><a href="{% url 'registercli' %}">Sign in</a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="#"><span>Organizer</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                <ul>
                  <li><a href="{% url 'login_view' %}">Log in</a></li>
                  <li><a href="{% url 'registerorg' %}">Sign in</a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="#"><span>Admin</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                <ul>
                  <li><a href="{% url 'login_view' %}">Log in</a></li>
                </ul>
              </li>
            </ul>
          </li>
          {% endif %}
          <!-- <li><a href="#contact">Contact</a></li> -->
        </ul>
      </nav><!-- .navbar -->

      <a class="btn-book-a-table" href="{% url 'events:event_listing' %}">Our events</a>
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header>
  <!-- End Header -->

users/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home page </title>
</head>
<body>
 <h1> welcome to the home page Mr. Django!!!!!!!!!!</h1>
 <span>{{user.username}}</span>
 <br>
 <span>{{user.social_media_link}}</span>
 <img src="../../media/{{user.organizer.image}}" width="100px" height="100px">
 <a href="{% url 'logout' %}">Logout</a>
</body>
</html>