EventSte/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('events/',include('events.urls')),
    path('bookings/',include('bookings.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

bookings/urls.py
from django.urls import path
from . import views
# from .views import OrganizerRegistrationView, ClientRegistrationView
from django.contrib.auth.decorators import login_required
app_name = 'bookings'


urlpatterns = [
path('event/<int:event_id>/book/', login_required(views.EventBooking), name='event_booking'),
path('event/<int:event_id>/', login_required(views.show_bookings), name='show_bookings'),
path('client/', login_required(views.client_bookings), name='client_bookings'),
path('validate_booking/<str:booking_id>/', login_required(views.validate_booking), name='validate_booking'),

]

events/urls.py
from django.urls import include,path
from . import views
# from .views import OrganizerRegistrationView, ClientRegistrationView
from django.contrib.auth.decorators import login_required
app_name = 'events'


urlpatterns = [
    path('organizer', login_required(views.index1), name='manage_org'),
    path('admin', login_required(views.index2), name='manage_adm'),
    path('create/', login_required(views.create_event), name='create'),
    path('update/<int:event_id>/', login_required(views.update_event), name='update_event'),
     path('<int:event_id>/', views.event_detail, name='event_detail'),
    path('event/validate/<int:event_id>/', login_required(views.validate_event), name='validate_event'),
    path('', views.event_listing, name='event_listing'),
]

users/urls.py
# urls.py
from django.urls import path
from . import views
# from .views import OrganizerRegistrationView, ClientRegistrationView
from django.contrib.auth.decorators import login_required


urlpatterns = [
path('', views.index, name= 'index'),
path('login/', views.login_view, name='login_view'),
path('register_client/', views.register_client, name='registercli'),
path('register_organizer/', views.register_organizer, name='registerorg'),
path('Dashboard/', login_required(views.dashboard_show), name='dash'),
path('logout/', views.logout_view, name='logout'),
# path('search/', views.event_search, name='event_search'),
path('search/', views.search_events, name='search_events'),
path('clients/admin/', login_required(views.manage_clients), name='manage_clients'),
path('organizers/admin/', login_required(views.manage_organizers), name='manage_organizers'),
path('validate_organizer/<int:id>/', login_required(views.validate_organizer), name='validate_organizer'),
path('profile/admin/', login_required(views.admin_profile), name='admin_profile'),
path('organizer/profile/', login_required(views.organizer_profile), name='organizer_profile'),
path('client/profile/',login_required(views.client_profile), name='client_profile'),
 path('organizer/deactivate/<int:organizer_id>/', login_required(views.deactivate_organizer), name='deactivate_organizer'),

]

bookings/models.py
from django.db import models
from users.models import User,Organizer,Client
from events.models import Event,EventCategory

class Booking(models.Model):
    booking_id = models.AutoField(primary_key=True)
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    status_choices = [
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('cancelled', 'Cancelled'),
    ]
    status = models.CharField(max_length=20, choices=status_choices, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Booking #{self.booking_id} - {self.client.username}"

class TicketBookingType(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    ticket_type = models.CharField(max_length=20)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.ticket_type} - {self.booking}"

bookings/views.py
from django.shortcuts import render,redirect,get_object_or_404
from events.models import Event
from .models import Booking,TicketBookingType
from django.db.models import F
from django.contrib import messages

# Create your views here.
def EventBooking(request,event_id) :
    event = Event.objects.get(pk=event_id)
    quantities = {
                'standard': int(request.POST.get('standard_quantity')),
                'mid': int(request.POST.get('mid_quantity')),
                'vip': int(request.POST.get('vip_quantity'))
            }
    if quantities['standard'] > event.standard_left or quantities['mid'] > event.mid_left or quantities['vip'] > event.vip_left :
        messages.error(request, 'You have exceeded the number of tickets')
        return redirect('events:event_detail', event_id=event.event_id)

    else :
            total_quantity = sum(quantities.values())
                # Update the quantity_left field
            event.quantity_left = F('quantity_left') - total_quantity
            event.standard_left -= quantities['standard']
            event.standard_left -= quantities['mid'] 
            quantities['vip'] -= event.vip_left 
            event.save()
            
            event = Event.objects.get(pk=event_id)
            booking = Booking.objects.create(
                    event=event,
                    client=request.user,
                    quantity=total_quantity,
                    total_price=event.calculate_total_price(quantities),
                )
                 # Create TicketBookingType instances for each ticket type
            for ticket_type, quantity in quantities.items():
                 if quantity > 0:
                    TicketBookingType.objects.create(
                    booking=booking,
                     ticket_type=ticket_type,
                    quantity=quantity
             )
            return redirect('bookings:client_bookings')
    
def show_bookings(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    bookings = Booking.objects.filter(event=event).order_by('-status')
    context = {
        'event': event,
        'bookings': bookings,
    }
    return render(request, 'event_bookings.html', context)

def client_bookings(request):
    # Retrieve bookings for the client
    bookings = Booking.objects.filter(client=request.user)

    # Retrieve booking ticket types for each booking
    booking_ticket_types = []
    for booking in bookings:
        ticket_types = TicketBookingType.objects.filter(booking=booking)
        booking_ticket_types.append((booking, ticket_types))

    context = {
        'bookings': booking_ticket_types
    }

    return render(request, 'manage_client_bookings.html', context)

def validate_booking(request, booking_id):
    booking = get_object_or_404(Booking, booking_id=booking_id)
        # Update the booking status to 'confirmed'
    booking.status = 'confirmed'
    booking.save()
    return redirect('bookings:show_bookings', event_id=booking.event.event_id)  # Replace with your success URL

bookings/templates/event_bookings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - Mazer Admin Dashboard</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/iconly/bold.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/perfect-scrollbar/perfect-scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.svg' %}" type="image/x-icon">
</head>

<body>
    <div id="app">
        {% include 'org_sidebar.html' %}
        <div id="main">
          <header class="mb-3">
              <a href="#" class="burger-btn d-block d-xl-none">
                  <i class="bi bi-justify fs-3"></i>
              </a>
          </header>

          <div class="page-heading">
              <h3></h3>
          </div>
          <div class="page-heading">
              <div class="page-title">
                  <div class="row">
                      <div class="col-12 col-md-6 order-md-1 order-last mb-5">
                          <h3>{{event.name}} - Booking details</h3>
                      </div>
                      <div class="col-12 col-md-6 order-md-2 order-first">
                          <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                              <ol class="breadcrumb">
                                  <li class="breadcrumb-item"><a href="/Dashboard">Dashboard</a></li>
                                  <li class="breadcrumb-item"><a href="{% url 'events:manage_org' %}">Events details</a></li>
                                  <li class="breadcrumb-item active" aria-current="page">Booking details</li>
                              </ol>
                          </nav>
                      </div>
                  </div>
              </div>
              <section class="section">
                  <div class="card">
                      <div class="card-header">
                          Details
                      </div>
                      <div class="card-body">
                        {% if bookings %}
                          <table class="table table-striped" id="table1">
                              <thead>
                                  <tr>
                                      <th>Client</th>
                                      <th>Ticket Types</th>
                                      <th>Total price</th>
                                      <th>Status</th>
                                      <th>Action</th>
                                  </tr>
                              </thead>
                              <tbody>
                                {% for booking in bookings %}
                                  <tr>
                                    <td>{{ booking.client.username }}</td>
                                    <td>
                                      {% for ticket_booking in booking.ticketbookingtype_set.all %}
                                        {{ ticket_booking.ticket_type }}: {{ ticket_booking.quantity }} tickets<br>
                                      {% endfor %}
                                    </td>
                                    <td>{{ booking.total_price }} Dhs</td>
                                    <td>
                                      {% if booking.status == 'confirmed' %}
                                          <span class="badge bg-success">Confirmed</span>
                                      {% elif booking.status == 'cancelled' %}
                                          <span class="badge bg-danger">Cancelled</span>
                                      {% else %}
                                          <span class="badge bg-danger">Pending</span>
                                      {% endif %}
                                    </td>
                                    <td>
                                      {% if booking.status == 'pending' %}
                                      <form method="POST" action="{% url 'bookings:validate_booking' booking_id=booking.booking_id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-success">Validate</button>
                                      </form>
                                      {% endif %}
                                    </td>
                                  </tr>
                                {% endfor %}
                              </tbody>
                          </table>
                        {% else %}
                          <p>No bookings found for this event.</p>
                        {% endif %}
                      </div>
                  </div>
              </section>   
          </div>
          <footer>
            <div class="footer clearfix mb-0 text-muted">
                <div class="float-start">
                    <p>2023 &copy; AYB @ JML</p>
                </div>
            </div>
          </footer>
        </div>
    </div>
    <script src="{% static 'vendors/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendors/apexcharts/apexcharts.js' %}"></script>
    <script src="{% static 'js/pages/dashboard.js' %}"></script>
    <script src="{% static 'js/main/main.js' %}"></script>
</body>
</html>

bookings/templates/manage_client_bookings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - Users</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/iconly/bold.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/perfect-scrollbar/perfect-scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.svg' %}" type="image/x-icon">
</head>

<body>
    <div id="app">
        {% include 'client_sidebar.html' %}
        <div id="main">
            <header class="mb-3">
                <a href="#" class="burger-btn d-block d-xl-none">
                    <i class="bi bi-justify fs-3"></i>
                </a>
            </header>
  
            <div class="page-heading">
                <h3></h3>
            </div>
            <div class="page-heading">
                <div class="page-title">
                    <div class="row">
                        <div class="col-12 col-md-6 order-md-1 order-last mb-5">
                            <h3>Event details</h3>
                        </div>
                        <div class="col-12 col-md-6 order-md-2 order-first">
                            <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="Dashboard-admin.html">Dashboard</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Events details</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
        <section class="section">
            <div class="card">
                <div class="card-header">
                    Details
                </div>
                <div class="card-body">
                    <table class="table table-striped" id="table1">
                        <thead>
                            <tr>
                                <th>Event</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Location</th>
                                <th>Quantity</th>
                                <th>Tickets</th>
                                <th>Total Price</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for booking, ticket_types in bookings %}
                            <tr>
                                <td><a href="{%url 'events:event_detail' event_id=booking.event.event_id%}">{{ booking.event.name }}</a></td>
                                <td>{{ booking.event.start_datetime }}</td>
                                <td>{{ booking.event.end_datetime }}</td>
                                <td>{{ booking.event.location }}</td>
                                <td>{{ booking.quantity }}</td>
                                <td> 
                                    <ul>
                                        {% for ticket_type in ticket_types %}
                                            <li>{{ ticket_type.ticket_type }} - Quantity: {{ ticket_type.quantity }}</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                                <td>{{ booking.total_price }} Dhs</td>
                                <td>
                                    {% if booking.status == 'confirmed' %}
                                        <span class="badge bg-success">Confirmed</span>
                                    {% elif booking.status == 'cancelled' %}
                                        <span class="badge bg-danger">Cancelled</span>
                                    {% else %}
                                    <span class="badge bg-danger">Pending</span>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </section>   
        </div>
        </div>

    <footer>
        <div class="footer clearfix mb-0 text-muted">
            <div class="float-start">
                <p>2023 &copy; AYB & JML</p>
            </div>
        </div>
    </footer>

    <script src="{% static 'vendors/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendors/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'vendors/apexcharts/apexcharts.js' %}"></script>
    <script src="{% static 'js/pages/dashboard.js' %}"></script>
    <script src="{% static 'js/main/main.js' %}"></script>
    <script>
        // Simple Datatable
        let table1 = document.querySelector('#table1');
        let dataTable = new simpleDatatables.DataTable(table1);
    </script>
</body>

</html>