EventSte/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('events/',include('events.urls')),
    path('bookings/',include('bookings.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

bookings/urls.py
from django.urls import path
from . import views
# from .views import OrganizerRegistrationView, ClientRegistrationView
from django.contrib.auth.decorators import login_required
app_name = 'bookings'


urlpatterns = [
path('event/<int:event_id>/book/', login_required(views.EventBooking), name='event_booking'),
path('event/<int:event_id>/', login_required(views.show_bookings), name='show_bookings'),
path('client/', login_required(views.client_bookings), name='client_bookings'),
path('validate_booking/<str:booking_id>/', login_required(views.validate_booking), name='validate_booking'),

]

events/urls.py
from django.urls import include,path
from . import views
# from .views import OrganizerRegistrationView, ClientRegistrationView
from django.contrib.auth.decorators import login_required
app_name = 'events'


urlpatterns = [
    path('organizer', login_required(views.index1), name='manage_org'),
    path('admin', login_required(views.index2), name='manage_adm'),
    path('create/', login_required(views.create_event), name='create'),
    path('update/<int:event_id>/', login_required(views.update_event), name='update_event'),
     path('<int:event_id>/', views.event_detail, name='event_detail'),
    path('event/validate/<int:event_id>/', login_required(views.validate_event), name='validate_event'),
    path('', views.event_listing, name='event_listing'),
]

users/urls.py
# urls.py
from django.urls import path
from . import views
# from .views import OrganizerRegistrationView, ClientRegistrationView
from django.contrib.auth.decorators import login_required


urlpatterns = [
path('', views.index, name= 'index'),
path('login/', views.login_view, name='login_view'),
path('register_client/', views.register_client, name='registercli'),
path('register_organizer/', views.register_organizer, name='registerorg'),
path('Dashboard/', login_required(views.dashboard_show), name='dash'),
path('logout/', views.logout_view, name='logout'),
# path('search/', views.event_search, name='event_search'),
path('search/', views.search_events, name='search_events'),
path('clients/admin/', login_required(views.manage_clients), name='manage_clients'),
path('organizers/admin/', login_required(views.manage_organizers), name='manage_organizers'),
path('validate_organizer/<int:id>/', login_required(views.validate_organizer), name='validate_organizer'),
path('profile/admin/', login_required(views.admin_profile), name='admin_profile'),
path('organizer/profile/', login_required(views.organizer_profile), name='organizer_profile'),
path('client/profile/',login_required(views.client_profile), name='client_profile'),
 path('organizer/deactivate/<int:organizer_id>/', login_required(views.deactivate_organizer), name='deactivate_organizer'),

]

events/models.py
from django.db import models
from users.models import User,Organizer,Client

# Create your models here.
class Category(models.Model):
    category_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Event(models.Model):
    event_id = models.AutoField(primary_key=True)
    organizer = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, through='EventCategory')
    name = models.CharField(max_length=255)
    description = models.TextField()
    start_datetime = models.DateTimeField(null=True,blank=True)
    end_datetime = models.DateTimeField(null=True,blank=True)
    quantity_left = models.PositiveIntegerField()
    location = models.CharField(max_length=255)
    image = models.ImageField(upload_to='event_images/')
    standard = models.DecimalField(null=True,max_digits=8, decimal_places=2)
    mid = models.DecimalField(null=True,max_digits=8, decimal_places=2) 
    vip = models.DecimalField(null=True,max_digits=8, decimal_places=2)  
    standard_left = models.PositiveIntegerField(null=True)
    mid_left = models.PositiveIntegerField(null=True) 
    vip_left = models.PositiveIntegerField(null=True) # Add price field here
    status_choices = [
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('cancelled', 'Cancelled'),
        ('finished', 'Finished'),
    ]
    status = models.CharField(max_length=50, choices=status_choices, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def calculate_total_price(self, quantities):
        ticket_prices = {
            'standard': self.standard,
            'mid': self.mid,
            'vip': self.vip
        }
      
        total_price = 0
        for ticket_type, quantity in quantities.items():
            if quantity > 0 and ticket_type in ticket_prices:
                ticket_price = ticket_prices[ticket_type]
                total_price += ticket_price * quantity

        return total_price
    def update_event_fields(event, fields):
        for field_name, field_value in fields.items():
            if hasattr(event, field_name):
                setattr(event, field_name, field_value)
        event.save()
    # @property
    # def msg():
    #     return ""
    
class EventCategory(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Event: {self.event.name}, Category: {self.category.name}"
    

events/forms.py
from django import forms
from .models import Event,EventCategory,Category

class EventForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'category-checkbox'}),
        required=False,
        label='Categories',
    )

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['categories'].widget.choices = [(category.category_id, category.name) for category in Category.objects.all()]

    class Meta:
        model = Event
        fields = ['name', 'description','start_datetime' ,'end_datetime' ,'standard','mid','vip','standard_left','mid_left','vip_left','location', 'image']

    def clean_quantity_left(self):
        quantity_left = self.cleaned_data.get('quantity_left')
        if quantity_left and quantity_left < 0:
            raise forms.ValidationError("Quantity left must be a non-negative value.")
        return quantity_left

    def clean_end_date(self):
        start_datetime = self.cleaned_data.get('start_datetime')
        end_datetime = self.cleaned_data.get('end_datetime')
        if start_datetime and end_datetime and start_datetime >= end_datetime:
            raise forms.ValidationError("End date must be later than the start date.")
        return end_datetime
    
class EventUpdateForm(forms.ModelForm):
    name = forms.CharField(required=False)
    description = forms.CharField(required=False, widget=forms.Textarea)
    start_datetime = forms.DateTimeField(required=False)
    end_datetime = forms.DateTimeField(required=False)
    location = forms.CharField(required=False)
    image = forms.ImageField(required=False)
    standard = forms.DecimalField(required=False)
    mid = forms.DecimalField(required=False)
    vip = forms.DecimalField(required=False)
    standard_left = forms.IntegerField(required=False)
    mid_left = forms.IntegerField(required=False)
    vip_left = forms.IntegerField(required=False)
    status_choices = [
        ('',''),
        ('finished', 'Finished'),
        ('cancelled', 'Cancelled'),
    ]
    status = forms.TypedChoiceField(choices=status_choices, required=False)
    
    class Meta:
        model = Event
        fields = ['name', 'description', 'start_datetime', 'end_datetime', 'location', 'image', 'standard',
                  'mid', 'vip', 'standard_left', 'mid_left', 'vip_left', 'status']

events/views.py
from django.shortcuts import render
from .forms import EventForm,EventUpdateForm
from .models import Event,Category,EventCategory
# Create your views here.

def create_event(request):
    events = Event.objects.filter(organizer_id=request.user.id)
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.organizer_id = request.user.id  
            event.quantity_left = event.standard_left + event.mid_left + event.vip_left 
            event.save()
            categories = form.cleaned_data['categories']  # Get the selected categories from the form
            for category in categories:
                event.categories.add(category)
            context = {
        'events': events,
        'form' : EventForm(),
        'form1' : EventUpdateForm(),
         }

            return render(request, 'manage_event_org.html',context)  # Redirect to event detail page
    else:
        context = {
            'events': events,
            'form' : EventForm(),
            'form1' : EventUpdateForm(),
         }
        return render(request, 'manage_event_org.html',context )
    
def index1(request):
    events = Event.objects.filter(organizer_id=request.user.id)
    context = {
        'events': events,
        'form'  : EventForm(),
        'form1' : EventUpdateForm(),
        }
    return render(request, 'manage_event_org.html',context) 

def index2(request):
    pending_events = Event.objects.filter(status='pending')
    other_events = Event.objects.exclude(status='pending')
    events = list(pending_events) + list(other_events)
    context = {
        'events': events,
        }
    return render(request, 'manage_event_adm.html',context)
 
def validate_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    if event.status == 'pending':
        event.status = 'confirmed'
        event.save()
    return redirect('events:manage_adm')

from django.shortcuts import render, get_object_or_404, redirect
import logging
    
def update_event(request, event_id):
    event1 = Event.objects.get(pk=event_id)
    event = Event()
    if request.method == 'POST':
        form = EventUpdateForm(request.POST, instance=event)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            for field in form.fields:
                value = cleaned_data.get(field)
                if value:
                    setattr(event1, field, value)
            # dd(event)
            event1.save()
            return redirect('events:create')
    
def event_detail(request, event_id):
    event = get_object_or_404(Event, event_id=event_id)
    user = request.user
    return render(request, 'event_detail.html', {'event': event,'user':user})
 
def event_listing(request) :
    context = {
         'categories' : Category.objects.all(),
     }
    return render(request,'event_listing.html',context)

events/templates/manage_event_adm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - Mazer Admin Dashboard</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../static/css/bootstrap.css">

    <link rel="stylesheet" href="../../static/vendors/iconly/bold.css">

    <link rel="stylesheet" href="../../static/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="../../static/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="../../static/css/app.css">
    <link rel="shortcut icon" href="../static/images/favicon.svg" type="image/x-icon">
   
</head>
<body>
    <div id="app">
        {% include 'admin_sidebar.html' %}
        <div id="main">
          <header class="mb-3">
              <a href="#" class="burger-btn d-block d-xl-none">
                  <i class="bi bi-justify fs-3"></i>
              </a>
          </header>

          <div class="page-heading">
              <h3></h3>
          </div>
          <div class="page-heading">
              <div class="page-title">
                  <div class="row">
                      <div class="col-12 col-md-6 order-md-1 order-last mb-5">
                          <h3>Event details</h3>
                      </div>
                      <div class="col-12 col-md-6 order-md-2 order-first">
                          <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                              <ol class="breadcrumb">
                                  <li class="breadcrumb-item"><a href="Dashboard-admin.html">Dashboard</a></li>
                                  <li class="breadcrumb-item active" aria-current="page">Events details</li>
                              </ol>
                          </nav>
                      </div>
                  </div>
              </div>
              <section class="section">
                  <div class="card">
                      <div class="card-header">
                          Details and Management
                      </div>
                      <div class="card-body">
                        <table class="table table-striped" id="table1">
                            <thead>
                                <tr>
                                    <th>Organizer</th>
                                    <th>Event</th>
                                    <th>Categories</th>
                                    <th>Starts at</th>
                                    <th>Ends at</th>
                                    <th>Location</th>
                                    <th>Remaining tickets</th>
                                    <th>Image</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for event in events %}
                                <tr>
                                    <td>{{ event.organizer }}</td>
                                    <td><a href="{%url 'events:event_detail' event_id=event.event_id%}">{{event.name}}</a></td>
                                    <td>
                                        {% for category in event.categories.all %}
                                            {{ category.name }}
                                            {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                    </td>
                                    <td>{{ event.start_datetime }}</td>
                                    <td>{{ event.end_datetime }}</td>
                                    <td>{{ event.location }}</td>
                                    <td>{{ event.quantity_left }}</td>
                                    <td><img src="/media/{{event.image}}" class="event-image" alt="Event Image" id="myImg" style="width: 50%; max-width: 150px; cursor:pointer;"></td>
                                    <td>
                                      {% if event.status == 'confirmed' %}
                                        <span class="badge bg-success">Active</span>
                                      {%elif event.status == 'pending'%}
                                      <span class="badge bg-danger">Pending</span>
                                      {%elif event.status == 'finished'%}
                                      <span class="badge bg-success">Finished</span>
                                      {%else%}
                                      <span class="badge bg-danger">Cancelled</span>
                                     {% endif %}
                                    </td>
                                    <td>
                                      {% if event.status == 'pending' %}
                                      <form method="POST" action="{% url 'events:validate_event' event_id=event.event_id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-success">Validate</button>
                                      </form>
                                      {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    
                  </div>

              </section>
          </div>
          <footer>
              <div class="footer clearfix mb-0 text-muted">
                  <div class="float-start">
                      <p>2023 &copy; AYB @ JML</p>
                  </div>
              </div>
          </footer>
      </div>
  </div>

 <!-- The Modal -->
 <div id="myModal" class="modal-img">
    <span class="close">&times;</span>
    <img class="modal-content-img" id="img01">
    <div id="caption"></div>
  </div>
  




  <script src="../../static/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
  <script src="../../static/js/bootstrap.bundle.min.js"></script>
  
  <script src="../../static/vendors/apexcharts/apexcharts.js"></script>
  <script src="../../static/js/pages/dashboard.js"></script>
  
  <script src="../../static/js/main/main.js"></script>

 <script>
   // Simple Datatable
   let table1 = document.querySelector('#table1');
   let dataTable = new simpleDatatables.DataTable(table1);
 </script>

<script>
    // Get the modal
   // Get all car images with class name "car-image"
  var carImages = document.getElementsByClassName("event-image");
  
  // Get the modal element
  var modal = document.getElementById("myModal");
  var modalImg = document.getElementById("img01");
  // Get the <span> element that closes the modal
  var closeModal = document.getElementsByClassName("close")[0];
  
  // Iterate through each car image
  for (var i = 0; i < carImages.length; i++) {
    var image = carImages[i];
  
    // Set click event handler for each car image
    image.onclick = function() {
      // Get the clicked image source and alt text
      
      modal.style.display = "block";
      modalImg.src = this.src;
      captionText.innerHTML = this.alt;
      // Set the clicked image source and alt text in the modal
    };
  }
  
  // Close the modal when the close button is clicked
  closeModal.onclick = function() {
    modal.style.display = "none";
  };
  
  // Close the modal when the user clicks outside the modal content
  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  };
</script>

</body>

</html>

events/templates/manage_event_org.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Event</title>
    <!DOCTYPE html>
    <html lang="en">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dashboard - Mazer Admin Dashboard</title>
    
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="../../static/css/bootstrap.css">
    
        <link rel="stylesheet" href="../../static/vendors/iconly/bold.css">
    
        <link rel="stylesheet" href="../../static/vendors/perfect-scrollbar/perfect-scrollbar.css">
        <link rel="stylesheet" href="../../static/vendors/bootstrap-icons/bootstrap-icons.css">
        <link rel="stylesheet" href="../../static/css/pages/main.css">
        <link rel="stylesheet" href="../../static/css/app.css">
        <link rel="shortcut icon" href="../static/images/favicon.svg" type="image/x-icon">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        
    
</head>
<body>
  <div id="app">
    {% include 'org_sidebar.html' %}
    <div id="main">
      <header class="mb-3">
          <a href="#" class="burger-btn d-block d-xl-none">
              <i class="bi bi-justify fs-3"></i>
          </a>
      </header>
      <div class="page-heading">
          <div class="page-title">
              <div class="row">
                  <div class="col-12 col-md-6 order-md-1 order-last mb-5">
                      <h3>Event details</h3>
                  </div>
                  
                  <div class="col-12 col-md-6 order-md-2 order-first">
                      <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                          <ol class="breadcrumb">
                              <li class="breadcrumb-item"><a href="Dashboard-organizer.html">Dashboard</a></li>
                              <li class="breadcrumb-item active" aria-current="page">Even details</li>
                          </ol>
                      </nav>
                  </div>
              </div>
              <div class="col-xs-6">
                <a href="#addEventModal" class="btn btn-success" data-toggle="modal" style="
                margin-bottom: 20px;
                margin-left: 62em;
            "><span>Add New Event</span></a>				
              </div>
          </div>
          <section class="section">
            <div class="card">
                <div class="card-header">
                    Details and Management
                </div>
                <div class="card-body">
                  <table class="table table-striped" id="table1">
                      <thead>
                          <tr>
                              <th>Event</th>
                              <th>Categories</th>
                              <th>Starts at</th>
                              <th>Ends at</th>
                              <th>Location</th>
                              <th>Remaining tickets</th>
                              <th>Image</th>
                              <th>Status</th>
                              <th>Actions</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for event in events %}
                          <tr>
                            <td><a href="{% url 'bookings:show_bookings' event_id=event.event_id %}">{{ event.name }}</a></td>
                              <td>
                                  {% for category in event.categories.all %}
                                      {{ category.name }}
                                      {% if not forloop.last %}, {% endif %}
                                  {% endfor %}
                              </td>
                              <td>{{ event.start_datetime }}</td>
                              <td>{{ event.end_datetime }}</td>
                              <td>{{ event.location }}</td>
                              <td><ul><li>Standard : price: {{ event.standard }} Dhs, Quantity: {{ event.standard_left }}.</li><li>Mid : price: {{ event.mid }} Dhs, Quantity: {{ event.mid_left }}.</li><li>VIP : price: {{ event.vip }} Dhs, Quantity: {{ event.vip_left }}.</li></ul></td>
                              <td><img src="/media/{{event.image}}" class="event-image" alt="Car Image" id="myImg" style="width: 50%; max-width: 150px; cursor:pointer;"></td>
                              <td>
                                {% if event.status == 'confirmed' %}
                                  <span class="badge bg-success">Active</span>
                                {%elif event.status == 'pending'%}
                                <span class="badge bg-danger">Pending</span>
                                {%elif event.status == 'finished'%}
                                <span class="badge bg-success">Finished</span>
                                {%else%}
                                <span class="badge bg-danger">Cancelled</span>
                               {% endif %}
                              </td>
                              <td>
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#{{event.event_id}}">
                                  edit
                              </button> 
                              </td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>
              </div>
              
            </div>
        </section>
      </div>

      <footer>
        <div class="footer clearfix mb-0 text-muted">
            <div class="float-start">
                <p>2023 &copy; AYB @ JML</p>
            </div>
        </div>
    </footer>
</div>

<div class="modal fade" id="addEventModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create Event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" enctype="multipart/form-data" action ="{% url 'events:create' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="modal-footer">
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">add</button>
      </div>
    </form>
    </div>
  </div>
</div>

    {% for event in events %} 
     <div class="modal fade" id="{{event.event_id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Edit event</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form method="POST" action="{% url 'events:update_event' event_id=event.event_id %}">
  
                {% csrf_token %}
                {{ form1.as_p }}
              
              
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
          </form>
          </div>
        </div>
      </div>
    {% endfor %}
<div id="myModal" class="modal-img">
  <!-- The Close Button -->
  <span class="close">&times;</span>
  <!-- Modal Content (The Image) -->
  <img class="modal-content-img" id="img01">
  <!-- Modal Caption (Image Text) -->
  <div id="caption"></div>
</div>


</script>
<script src="../../static/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="../../static/js/bootstrap.bundle.min.js"></script>
<script src="../../static/vendors/simple-datatables/simple-datatables.js"></script>
<!-- <script src="../../static/vendors/apexcharts/apexcharts.js"></script>
<script src="../../static/js/pages/dashboard.js"></script> -->
<script src="../../static/js/main/main.js"></script>
<script>
  // Simple Datatable
  let table1 = document.querySelector('#table1');
  let dataTable = new simpleDatatables.DataTable(table1);
</script>

<script>
  // Get the modal
  // Get all car images with class name "car-image"
  var carImages = document.getElementsByClassName("event-image");
  
  // Get the modal element
  var modal = document.getElementById("myModal");
  var modalImg = document.getElementById("img01");
  // Get the <span> element that closes the modal
  var closeModal = document.getElementsByClassName("close")[0];
  
  // Iterate through each car image
  for (var i = 0; i < carImages.length; i++) {
  var image = carImages[i];
  
  // Set click event handler for each car image
  image.onclick = function() {
    // Get the clicked image source and alt text
    
    modal.style.display = "block";
    modalImg.src = this.src;
    captionText.innerHTML = this.alt;
    // Set the clicked image source and alt text in the modal
  };
  closeModal.onclick = function() {
  modal.style.display = "none";
  };
  
  // Close the modal when the user clicks outside the modal content
  window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
  };
  }
  </script>
</body>

</html>